platform :ios, '10.0'
use_frameworks!

target 'App' do
  # Add your Pods here

  # Automatic Capacitor Pod dependencies, do not delete
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'TeamhiveCapacitorEmail', :path => '/Users/triniwiz/Documents/projects/plugins/capacitor/capacitor-email/demo/node_modules/@teamhive/capacitor-email'
  # Do not delete
end
